pipeline:
  name: jcnm-pipeline
  identifier: jcnmpipeline
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: jcnm-stage
        identifier: jcnmstage
        description: ""
        type: CI
        spec:
          cloneCodebase: false
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: newcok8s
              namespace: harness-delegate-ng
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: newcodockerhub
                    repo: ashokbaixus/ubuntu_apache2
                    tags:
                      - ubuntu_apache2
