pipeline:
  name: newco-harness-pipeline
  identifier: newcoharnesspipeline
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: ashokbaixus
        build: <+input>
  stages:
    - stage:
        name: neco-nginx
        identifier: neconginx
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: newcok8s
              namespace: harness-delegate-ng
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: newcodockerhub
                    repo: ashokbaixus
                    tags:
                      - newco-nginx-img
              - parallel:
                  - step:
                      type: Background
                      name: dind
                      identifier: dind
                      spec:
                        connectorRef: account.harnessImage
                        image: docker:dind
                        shell: Sh
                  - step:
                      type: AquaTrivy
                      name: AquaTrivy_1
                      identifier: AquaTrivy_1
                      spec:
                        target:
                          detection: auto
                          type: container
                        advanced:
                          log:
                            level: info
                          args: {}
                        privileged: true
                        mode: orchestration
                        config: default
                        image:
                          type: docker_v2
                          name: newco-nginx-img
                          tag: latest
                        resources:
                          limits:
                            memory: 2G
                            cpu: 1000m
                  - step:
                      type: Grype
                      name: Grype_1
                      identifier: Grype_1
                      spec:
                        target:
                          detection: auto
                          type: container
                        advanced:
                          log:
                            level: info
                          args: {}
                        privileged: true
                        mode: orchestration
                        config: default
                        image:
                          type: docker_v2
                          name: newco-nginx-img
                          tag: latest
                        resources:
                          limits:
                            memory: 2G
                            cpu: 1000m
          sharedPaths:
            - /var/run
